# Generated by Django 5.0 on 2023-12-29 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juice_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='juice/')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juices', to='glory.juice')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('order_check', models.CharField(choices=[('Order Place', 'Order Place'), ('Order Confirm', 'Order Confirm'), ('Order Delivered', 'Order Delivered')], default='Order Place', max_length=100)),
                ('juice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juicess', to='glory.juice')),
            ],
        ),
    ]
